title: Hung Bui
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  A self-motivated learner with enthusiasm for Computer Science and adaptability to challenges, seeking knowledge and experience in professional environments
  <br><br>
  <a href="mailto: quanghungbui8104@gmail.com"><img src="icons8-mail-48.png"> Email</a>
  <br><br>
  <a href="https://www.linkedin.com/in/hùng-bùi-010a77251/"><img width="15px" src ="./images/LinkedIn_icon_circle.svg.png"> LinkedIn</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
